export const SERVICE_CATEGORIES = [
  {
    id: 'engineer-interior',
    name: 'Engineer/Architect',
    icon: '🏗️',
    description: 'Engineering and Interior Design Services',
    basePrice: 99,
    image: require('../assets/images/engineer.jpg'),
  },
  {
    id: 'plumber',
    name: 'Plumbing technician',
    icon: '🔧',
    description: 'Plumbing and Water Related Services',
    basePrice: 99,
    image: require('../assets/images/plumber.jpg'),
  },
  {
    id: 'granite-tiles',
    name: 'Dense/Expert layers',
    icon: '🏠',
    description: 'Floor and Wall Tiling Services',
    basePrice: 99,
    image: require('../assets/images/tiles.jpg'),
  },
  {
    id: 'painting',
    name: "Painters/wall pannels",
    icon: '🎨',
    description: 'Painting Services',
    basePrice: 99,
    image: require('../assets/images/painting.jpg'),
  },
  {
    id: 'contact-building',
    name: 'Contractors',
    icon: '🏢',
    description: 'Construction and Building Services',
    basePrice: 99,
    image: require('../assets/images/labors.jpg'),
  },
  {
    id: 'labor',
    name: "Labour's",
    icon: '👷',
    description: 'General Labor Services',
    basePrice: 0, // Free for labor category
    image: require('../assets/images/contractors.jpg'),
  },
  {
    id: 'mason-mastri',
    name: 'Masion/Mastri',
    icon: '🧱',
    description: 'Masonry and Construction Work',
    basePrice: 99,
    image: require('../assets/images/mistri.jpg'),
  },
  {
    id: 'interiors-building',
    name: "Interior designer's",
    icon: '🏠',
    description: 'Interior Building Services',
    basePrice: 99,
    image: require('../assets/images/interior.jpg'),
  },
  {
    id: 'stainless-steel',
    name: 'MS & SS Fitters',
    icon: '⚙️',
    description: 'Metal Work and Steel Services',
    basePrice: 99,
    image: require('../assets/images/steel.jpeg'),
  },
  {
    id: 'cleaning',
    name: 'Cleaning Operatives',
    icon: '🧹',
    description: 'Professional cleaning services',
    basePrice: 99,
    image: require('../assets/images/cleaning.jpg'),
  },
  {
    id: 'glass-mirror',
    name: 'Glazier & Mirror Installer',
    icon: '🪞',
    description: 'Glass and Mirror Installation Services',
    basePrice: 99,
    image: require('../assets/images/mirrior.jpg'),
  },
  {
    id: 'borewell',
    name: 'Borewell Drillers',
    icon: '💧',
    description: 'Borewell drilling and maintenance services',
    basePrice: 99,
    image: require('../assets/images/borewell.jpg'),
  },
];

export const getServiceById = (id: string) => {
  return SERVICE_CATEGORIES.find(service => service.id === id);
};